package com.spx.inventory_service.services;

import com.spx.inventory_service.dto.OfficeRequestDTO;
import com.spx.inventory_service.dto.OfficeResponseDTO;
import com.spx.inventory_service.mappers.OfficeMapper;
import com.spx.inventory_service.models.Office;
import com.spx.inventory_service.repositories.OfficeRepository;
import com.spx.inventory_service.utils.normalizer.OfficeRequestNormalizer;
import com.spx.inventory_service.utils.validator.CreateValidator;
import com.spx.inventory_service.utils.validator.ReadValidator;
import com.spx.inventory_service.utils.validator.UpdateValidator;
import jakarta.transaction.Transactional;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;
import java.util.List;

@Service
@Slf4j
public class OfficeService {

    @Autowired
    private OfficeRepository officeRepository;

    @Autowired
    private ReadValidator readValidator;

    @Autowired
    private CreateValidator createValidator;

    @Autowired
    private UpdateValidator updateValidator;

    @Autowired
    private OfficeMapper officeMapper;


    // ==========================================================
    // CRUD METHODS - From Repository Layer
    // ==========================================================

    // ==========================================================
    // READ OPERATIONS
    // ==========================================================

    /**
     * Gets all offices.
     *
     * @return the all offices
     */
    @Cacheable("offices-all")
    public List<OfficeResponseDTO> getAllOffices() {

        log.info("Service getAllOffices");

        /* Uses OfficeMapperImpl (auto-generated by MapStruct)
        to convert each Office entity into a DTO object. */
        return officeRepository.findAll()
                                .stream()
                                .map(officeMapper::toDTO)
                                .toList();
    }


    /**
     * Gets office by name.
     *
     * @param name the name
     * @return the office by name
     */
    @Cacheable(value = "offices-by-name", key = "T(com.spx.inventory_service.utils.TextNormalizer).normalizeKey(#name)")
    public OfficeResponseDTO getOfficeByName(String name) {

        // Step 1: Check if the input Office entity is found and validate its name
        Office office = readValidator.checkIfEntityIsFound("Office", name, officeRepository::findByNameIgnoreCase);

        log.info("Service getOfficeByName");

        // Step 2: Mapper converts the entity into a DTO for response.
        return officeMapper.toDTO(office);
    }


    // ==========================================================
    // CREATE OPERATION
    // ==========================================================

    /**
     * Create office office response dto.
     *
     * @param newOfficeDTO the new office dto
     * @return the office response dto
     */
    @Transactional
    @CacheEvict(value = { "offices-all", "offices-by-name" }, allEntries = true)
    public OfficeResponseDTO createOffice(OfficeRequestDTO newOfficeDTO) {

        // Step 1. Check if the input Office entity already exists and validate its fields
        OfficeRequestDTO normalizedDTO = createValidator.checkIfEntityAlreadyExists("Office", newOfficeDTO,
               dto -> officeRepository.existsByNameIgnoreCase(dto.getOfficeName()), OfficeRequestNormalizer::normalize);

        // Step 2. Convert DTO -> Entity (Database added an id automatically)
        Office newOfficeEntity = officeMapper.toEntity(normalizedDTO);

        // Step 3. Save the entity into the database
        Office savedOfficeEntity = officeRepository.save(newOfficeEntity);

        log.info("Office created. Name: {}", savedOfficeEntity.getName());

        // Step 4. Convert Entity -> DTO
        return officeMapper.toDTO(savedOfficeEntity);
    }


    // ==========================================================
    // UPDATE OPERATION
    // ==========================================================

    /**
     * Update existing office by name office response dto.
     *
     * @param currentName  the current name
     * @param newOfficeDTO the new office dto
     * @return the office response dto
     */
    @Transactional
    @CacheEvict(value = { "offices-all", "offices-by-name" }, allEntries = true)
    public OfficeResponseDTO updateExistingOfficeByName(String currentName, OfficeRequestDTO newOfficeDTO) {

        // Step 1: Check if the input Office (old office) entity is found and validate its name
        Office existingOffice = readValidator.checkIfEntityIsFound("Office", currentName, officeRepository::findByNameIgnoreCase);

        // Step 2: Normalize incoming new office DTO
        OfficeRequestDTO normalizedNewOffice = OfficeRequestNormalizer.normalize(newOfficeDTO);

        // Step 3: Extract the new office name
        String newOfficeName = normalizedNewOffice.getOfficeName();

        // Step 4: UpdateValidator
        updateValidator.checkIfUpdateIsAllowed("Office", existingOffice.getName(), newOfficeName, officeRepository::existsByNameIgnoreCase);

        // Step 5: Update only mutable fields (in this case: office name).
        existingOffice.setName(newOfficeName);

        // Step 6: Save the new updated Office into the database
        Office updatedOffice = officeRepository.save(existingOffice);

        // Step 7: Convert Entity -> DTO
        return officeMapper.toDTO(updatedOffice);
    }


    // ==========================================================
    // DELETE OPERATION
    // ==========================================================

    /**
     * Delete office by name.
     *
     * @param officeName the office name
     */
    @Transactional
    @CacheEvict(value = { "offices-all", "offices-by-name" }, allEntries = true)
    public void deleteOfficeByName(String officeName) {

        // Step 1: Check if the input Office entity is found and validate its name
        Office office = readValidator.checkIfEntityIsFound("Office", officeName, officeRepository::findByNameIgnoreCase);

        // Step 2: Extract the normalized office name
        String normalizedOfficeName = office.getName();

        // Step 3: Proceed with deletion.
        officeRepository.deleteByNameIgnoreCase(normalizedOfficeName);

        log.info("Deleting office. Named: {}", normalizedOfficeName);

    }
}