package com.spx.inventory_management.services;

import com.spx.inventory_management.dto.OfficeRequestDTO;
import com.spx.inventory_management.dto.OfficeResponseDTO;
import com.spx.inventory_management.mappers.OfficeMapper;
import com.spx.inventory_management.models.Office;
import com.spx.inventory_management.repositories.OfficeRepository;
import com.spx.inventory_management.utils.OfficeRequestNormalizer;
import com.spx.inventory_management.utils.TextNormalizer;
import jakarta.persistence.EntityNotFoundException;
import jakarta.transaction.Transactional;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;
import java.util.List;

@Service
@Slf4j
public class OfficeService {

    @Autowired
    private OfficeRepository officeRepository;

    @Autowired
    private OfficeMapper officeMapper;


    // ==========================================================
    // CRUD METHODS - From Repository Layer
    // ==========================================================

    // ==========================================================
    // READ OPERATIONS
    // ==========================================================

    @Cacheable("offices")
    public List<OfficeResponseDTO> getAllOffices() {

        /* Uses OfficeMapperImpl (auto-generated by MapStruct)
        to convert each Office entity into a DTO object. */
        return officeRepository.findAll()
                                .stream()
                                .map(officeMapper::toDTO)
                                .toList();
    }


    // ATTENTION: Cache use a not normalized value
    @Cacheable(value = "offices", key = "#name")
    public OfficeResponseDTO getOfficeByName(String name) {

        // Step 1: Normalized the incoming name
        String normalizedName = TextNormalizer.normalizeKey(name);

        // Step 2: Repository try to retrieve an Office entity by its unique name from the database.
        Office office = officeRepository.findByNameIgnoreCase(normalizedName).orElseThrow(() -> {
            log.error("Office not found. Name:{}", normalizedName);
            return new EntityNotFoundException("Office not found"); // Throw 404 HTTP Status code
        });

        // Step 3: Mapper converts the entity into a DTO for response.{
        return officeMapper.toDTO(office);
    }


    // ==========================================================
    // CREATE OPERATION
    // ==========================================================

    @Transactional
    public OfficeResponseDTO createOffice(OfficeRequestDTO newOfficeDTO) {

        // Step 1: Normalize all the input field incoming from OfficeRequestDTO
        OfficeRequestDTO normalizedDTO = OfficeRequestNormalizer.normalize(newOfficeDTO);

        // Step 2: Check if the office name already exists
        if (officeRepository.existsByNameIgnoreCase(normalizedDTO.getOfficeName())) {
            throw new IllegalArgumentException("Office name already exists: " + normalizedDTO.getOfficeName());
        }

        // Step 3. Convert DTO -> Entity (Database added an id automatically)
        Office newOfficeEntity = officeMapper.toEntity(normalizedDTO);

        // Step 4. Save the entity into the database
        Office savedOfficeEntity = officeRepository.save(newOfficeEntity);

        log.info("Office created. name={}", savedOfficeEntity.getName());

        // Step 5. Convert Entity -> DTO
        return officeMapper.toDTO(savedOfficeEntity);
    }


    // ==========================================================
    // UPDATE OPERATION
    // ==========================================================

    @Transactional
    public OfficeResponseDTO updateExistingOfficeByName(String currentName, OfficeRequestDTO newOfficeDTO) {

        // Step 1: Normalize the current name
        String normalizedCurrentName = TextNormalizer.normalizeKey(currentName);

        // Step 2: Normalize incoming new office data
        OfficeRequestDTO normalizedNewOffice = OfficeRequestNormalizer.normalize(newOfficeDTO);

        // Step 3: Retrieve the existing office or throw if not found.
        Office existingOffice = officeRepository.findByNameIgnoreCase(normalizedCurrentName).orElseThrow(() -> {
            log.error("Update failed. Office not found. Name:{}", normalizedCurrentName);
             return new EntityNotFoundException("Office not found");
        });

        // Step 4: Extract the new office name
        String newOfficeName = normalizedNewOffice.getOfficeName();

        // Step 5: If the newName IS NOT EQUAL to the currentName AND if the newName already exists into the database...
        if (!normalizedCurrentName.equalsIgnoreCase(newOfficeName) && officeRepository.existsByNameIgnoreCase(newOfficeName)) {
            throw new IllegalArgumentException("Office name already exists: " + newOfficeName);
        }

        // Step 6: Update only mutable fields (in this case: office name).
        existingOffice.setName(newOfficeName);

        // Step 7: Save the new updated Office into the database
        Office updatedOffice = officeRepository.save(existingOffice);

        log.info("Office updated. OldName:{}, NewName:{}", normalizedCurrentName, newOfficeName);

        // Step 8: Convert Entity -> DTO
        return officeMapper.toDTO(updatedOffice);
    }


    // ==========================================================
    // DELETE OPERATION
    // ==========================================================

    @Transactional
    public void deleteOfficeByName(String officeName) {

        // Step 1: Normalize the office name
        String normalizedName = TextNormalizer.normalizeKey(officeName);

        // Step 2: Validate entity existence before deletion.
        if (!officeRepository.existsByNameIgnoreCase(normalizedName)) {
            log.error("Delete failed. Office not found. Name:{}", normalizedName);
            throw new EntityNotFoundException("Office not found");
        }

        // Step 3: Proceed with deletion.
        officeRepository.deleteByNameIgnoreCase(normalizedName);

        log.info("Deleting office. Named:{}", normalizedName);

    }
}