package com.spx.inventory_management.controllers;

import com.spx.inventory_management.dto.OfficeRequestDTO;
import com.spx.inventory_management.dto.OfficeResponseDTO;
import com.spx.inventory_management.mapper.OfficeMapper;
import com.spx.inventory_management.models.Office;
import com.spx.inventory_management.services.OfficeService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.stream.Collectors;

/**
 * REST Controller responsible for managing Office-related operations.
 *
 * This controller exposes CRUD endpoints for the "offices" resource.
 * It uses DTOs to isolate API contracts from internal JPA entities.
 * The mapping between DTOs and entities is handled by MapStruct.
 *
 */
@RestController
@RequestMapping("/offices")
public class OfficeController {

    @Autowired
    public OfficeService officeService;

    @Autowired
    public OfficeMapper mapper;

    // ==========================================================
    // CRUD METHODS - Service Layer Integration
    // ==========================================================

    /**
     * Retrieves all offices stored in the database.
     *
     * @return a list of {@link OfficeResponseDTO} objects representing all offices.
     *
     * Example JSON response:
     * [
     *   { "id": 1, "officeName": "Milan HQ" },
     *   { "id": 2, "officeName": "Rome Office" }
     * ]
     */
    @GetMapping("/all")
    public List<OfficeResponseDTO> getAllOfficesDTO() {

        /* Uses OfficeMapperImpl (auto-generated by MapStruct)
        to convert each Office entity into a DTO object. */
        List <OfficeResponseDTO> officeResponseDTOS = officeService.getAllOffices()
                                                    .stream()
                                                    .map(mapper::toDTO)
                                                    .collect(Collectors.toList());

        return officeResponseDTOS;
    }

    /**
     * Retrieves an Office by its unique identifier.
     *
     * @param id the ID of the office to retrieve
     * @return an {@link OfficeResponseDTO} representing the requested office
     *
     * Example request: GET /offices/3
     * Example response: { "id": 3, "officeName": "Rome Office" }
     */
    @GetMapping("/{id}")
    public OfficeResponseDTO getOfficeDTOById(@PathVariable long id) {

        // Step 1: Service retrieves an Office entity by its unique ID.
        Office retrievedOffice = officeService.getOfficeById(id);

        // Step 2: Mapper converts the entity into a DTO for response.
        OfficeResponseDTO officeResponseDTO = mapper.toDTO(retrievedOffice);

        return officeResponseDTO;
    }

    /**
     * Inserts a new Office record into the database.
     *
     * @param newOfficeDTO the incoming DTO from the client request
     * @return an {@link OfficeResponseDTO} representing the saved office
     *
     * Example request body:
     *
     * { "officeName": "Turin HQ" }
     *
     * Example response:
     *
     * { "id": 5, "officeName": "Turin HQ" }
     *
     */
    @PostMapping("/insert")
    public OfficeResponseDTO createOffice(@RequestBody OfficeRequestDTO newOfficeDTO) {

        // Step 1: Convert incoming DTO to an Entity for persistence.
        Office newOffice = mapper.toEntity(newOfficeDTO);

        // Step 2: Persist the entity via service layer.
        Office savedOffice = officeService.createOffice(newOffice);

        // Step 3: Convert the persisted entity (with generated ID) back to a DTO.
        OfficeResponseDTO officeResponseDTO =  mapper.toDTO(savedOffice);

        return officeResponseDTO;
    }

    /**
     * Updates an existing Office record.
     *
     * @param id the ID of the office to update
     * @param updatedOfficeDTO DTO containing updated field values
     * @return an {@link OfficeResponseDTO} representing the updated office
     *
     * Example request:
     * PUT /offices/update/3
     *
     * { "officeName": "Turin Branch" }
     *
     * Example response:
     *
     * * { "id": 3, "officeName": "Turin Branch" }
     *
     */
    @PutMapping("/update/{id}")
    public OfficeResponseDTO updateOffice(@PathVariable long id, @RequestBody OfficeRequestDTO updatedOfficeDTO) {

        // Step 1: Convert incoming DTO into an entity containing updated values.
        Office updatedData = mapper.toEntity(updatedOfficeDTO);

        // Step 2: Delegate to service layer validation, update fields, and persist changes.
        Office updatedOffice = officeService.updateExistingOffice(id, updatedData);

        // Step 3: Convert the updated entity into a response DTO.
        OfficeResponseDTO officeResponseDTO =  mapper.toDTO(updatedOffice);

        return officeResponseDTO;
    }

    /**
     * Deletes an Office record by its ID.
     *
     * @param id the ID of the office to delete
     *
     * Example request:
     * DELETE /offices/3
     *
     * Returns HTTP 204 (No Content) upon success.
     */
    @DeleteMapping("/{id}")
    public void deleteOfficeById(@PathVariable long id) {

        // Delegate to service layer for deletion logic.
        officeService.deleteOfficeById(id);
    }
}