-- ============================================================
-- SCHEMA
-- ============================================================

CREATE TABLE IF NOT EXISTS offices (
   id_office BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS asset_types (
    id_asset_type BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_type_description VARCHAR(200),
    asset_type_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS assets (
    id_asset BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_date DATE,
    serial_number VARCHAR(50) NOT NULL UNIQUE,
    id_asset_type BIGINT NOT NULL,
    id_office BIGINT NOT NULL,
    FOREIGN KEY (id_office) REFERENCES offices(id_office),
    FOREIGN KEY (id_asset_type) REFERENCES asset_types(id_asset_type)
);

CREATE TABLE IF NOT EXISTS software_licenses (
    id_software_license BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expiration_date DATE NOT NULL,
    max_installations INTEGER,
    software_name VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS assets_licenses (
    license_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    PRIMARY KEY (license_id, asset_id),
    FOREIGN KEY (asset_id) REFERENCES assets(id_asset),
    FOREIGN KEY (license_id) REFERENCES software_licenses(id_software_license)
);



-- ============================================================
-- TO DELETE THE TABLES
-- ============================================================

-- DROP SCHEMA public CASCADE;
-- CREATE SCHEMA public;

